export default [
  {
    _id: "123",
    firstName: "Elon",
    lastName: "Musk",
    loginId: "elon",
    section: "S101",
    role: "STUDENT",
    lastActivity: "2 hours ago",
    totalActivity: "10:00:00",
  },
  {
    _id: "234",
    firstName: "Ada",
    lastName: "Lovelace",
    loginId: "ada",
    section: "S101",
    role: "TA",
    lastActivity: "1 day ago",
    totalActivity: "8:30:00",
  },
  {
    _id: "345",
    firstName: "Alan",
    lastName: "Turing",
    loginId: "alan",
    section: "S101",
    role: "FACULTY",
    lastActivity: "3 hours ago",
    totalActivity: "12:45:00",
  },
  {
    _id: "456",
    firstName: "Grace",
    lastName: "Hopper",
    loginId: "grace",
    section: "S101",
    role: "STUDENT",
    lastActivity: "5 minutes ago",
    totalActivity: "20:00:00",
  },
  {
    _id: "567",
    firstName: "Katherine",
    lastName: "Johnson",
    loginId: "kj",
    section: "S101",
    role: "STUDENT",
    lastActivity: "30 minutes ago",
    totalActivity: "9:15:00",
  },
  {
    _id: "789",
    firstName: "Tim",
    lastName: "Berners-Lee",
    loginId: "tim",
    section: "S102",
    role: "STUDENT",
    lastActivity: "2 days ago",
    totalActivity: "15:00:00",
  },
  {
    _id: "890",
    firstName: "Dennis",
    lastName: "Ritchie",
    loginId: "dennis",
    section: "S102",
    role: "STUDENT",
    lastActivity: "1 hour ago",
    totalActivity: "11:20:00",
  },
  {
    _id: "999",
    firstName: "Admin",
    lastName: "User",
    loginId: "admin",
    section: "S101",
    role: "ADMIN",
    lastActivity: "just now",
    totalActivity: "00:00:00",
  },
];
